create database perfildeprogramador;
use perfildeprogramador;

-- SELECT * FROM PAIS;
CREATE TABLE PAIS (
	ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(250),
    PRIMARY KEY (ID)
);

-- SELECT * FROM USUARIO;
CREATE TABLE USUARIO (
	ID int NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    NOMBRE VARCHAR(250),
    APELLIDO_PATERNO VARCHAR(250),
    APELLIDO_MATERNO VARCHAR(250),
    FECHA_NACIMIENTO DATE,
    FOTO VARCHAR(250),
    BIO TEXT,
    ID_PAIS INTEGER,
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID)
);

-- SELECT * FROM PROYECTOS;
CREATE TABLE PROYECTOS (
	ID int NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    URL VARCHAR(250),
    TITULO VARCHAR(250),
    ID_USUARIO INTEGER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

-- SELECT * FROM REDES_SOCIALES;
CREATE TABLE REDES_SOCIALES (
	ID int NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (ID),
    NOMBRE VARCHAR(250),
    URL VARCHAR(250),
    ICONO VARCHAR(250),
    ID_USUARIO INTEGER,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE PAIS (
    ID int NOT NULL AUTO_INCREMENT,
    NAME varchar(250)
);


